# https://developer.1password.com/docs/ssh/agent/config

# test: SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ssh-add -l

[[ssh-keys]]
item = "github ssh key"
vault = "Personal"
account = "Dany Dodson"

[[ssh-keys]]
item = "rawdog.pem"
vault = "Personal"
account = "Dany Dodson"

[[ssh-keys]]
item = "ollama ssh key"
vault = "Personal"
account = "Dany Dodson"