# https://developer.1password.com/docs/ssh/agent/config

# test: SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ssh-add -l

[[ssh-keys]]
item = "github_ssh"
vault = "Personal"
account = "Dany Dodson"

[[ssh-keys]]
item = "spatula"
vault = "Personal"
account = "Dany Dodson"

[[ssh-keys]]
item = "ollama_ssh"
vault = "Personal"
account = "Dany Dodson"

[[ssh-keys]]
item = "rawdog"
vault = "Personal"
account = "Dany Dodson"